apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: chache-volume
      mountPath: /data
  volumes:
  - name: chache-volume
    emptyDir: {}
  