apiVersion: v1
kind: Pod
metadata:
  name: multil-containers-pod
  labels:
    app: test
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
  - name: redis
    image: redis
  - name: busybox
    image: busybox