apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: limit
  name: limit
spec:
  containers:
  - image: busybox
    name: limit
    command: ["sleep","100000"]
    resources:
      limits:
        cpu: "200"
        memory: "200Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
