apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vip
  name: vip
spec:
  containers:
  - image: busybox
    name: vip
    resources: {}
    command: ["sleep", "3600"]
  nodeSelector:
    status: vip
  dnsPolicy: ClusterFirst
  restartPolicy: Always