apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cip
  name: cip
spec:
  containers:
  - image: busybox
    name: vip
    resources: {}
    command: ["sleep", "3600"]
  tolerations:
  - key: "key"
    value: "v"
    operator: "Equal"
    effect: "NoSchedule"
    dnsPolicy: ClusterFirst
  restartPolicy: Always