apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myredis
  template:
    metadata:
      labels:
        app: myredis
    spec:
      containers:
        - image: redis
          name: myredis
        readinessProbe:
          httpGet:
            port: 6379
          periodSeconds: 1
    