apiVersion: v1
kind: Pod
metadata:
  name: pod-env-secrets
  labels:
    app: pod-env-secrets
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","36000"]
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql
          key: passwd
      name: mysql
    