apiVersion: v1
kind: Pod
metadata:
  name: pod-mount-secrets
  labels:
    app: pod-mount-secrets
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","36000"]
    volumeMounts:
    - name: mysql
      mountPath: /mysql
  volumes:
  - name: mysql
    secret:
      secretName: mysql
    