apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
  labels:
    app: pod-with-pvc
spec:
  containers:
  - name: nginx
    image: nginx:1.18
    volumeMounts:
    - mountPath: /data
      name: my-claim
  volumes:
    - name: my-claim
      persistentVolumeClaim:
        claimName: my-claim