apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-one
spec:
  selector:
    matchLabels:
      app: ds-one
  template:
    metadata:
      labels:
        app: ds-one
    spec:
      containers:
      - name: nginx
        image: nginx:1.18